// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

#include "Cmd.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
}  // namespace pb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Cmd_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Cmd_2eproto = nullptr;
const uint32_t TableStruct_Cmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Cmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tCmd.proto\022\002pb*G\n\003CMD\022\017\n\013CMD_INVALID\020\000\022"
  "\025\n\020xLoginAccountCmd\020\351\007\022\030\n\023xLoginAccountA"
  "ckCmd\020\352\007B\006Z\004.;pbb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Cmd_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Cmd_2eproto = {
    false, false, 104, descriptor_table_protodef_Cmd_2eproto,
    "Cmd.proto",
    &descriptor_table_Cmd_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Cmd_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Cmd_2eproto,
    file_level_service_descriptors_Cmd_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Cmd_2eproto_getter() {
  return &descriptor_table_Cmd_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Cmd_2eproto(&descriptor_table_Cmd_2eproto);
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CMD_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Cmd_2eproto);
  return file_level_enum_descriptors_Cmd_2eproto[0];
}
bool CMD_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 1002:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
