// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataConfig.proto

#include "DataConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
PROTOBUF_CONSTEXPR GuiConfig_UIItem::GuiConfig_UIItem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.layout_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.script_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.layer_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GuiConfig_UIItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GuiConfig_UIItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GuiConfig_UIItemDefaultTypeInternal() {}
  union {
    GuiConfig_UIItem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GuiConfig_UIItemDefaultTypeInternal _GuiConfig_UIItem_default_instance_;
PROTOBUF_CONSTEXPR GuiConfig::GuiConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.item_list_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GuiConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GuiConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GuiConfigDefaultTypeInternal() {}
  union {
    GuiConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GuiConfigDefaultTypeInternal _GuiConfig_default_instance_;
PROTOBUF_CONSTEXPR BPConfig_BPItem::BPConfig_BPItem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bp_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lua_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BPConfig_BPItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BPConfig_BPItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BPConfig_BPItemDefaultTypeInternal() {}
  union {
    BPConfig_BPItem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BPConfig_BPItemDefaultTypeInternal _BPConfig_BPItem_default_instance_;
PROTOBUF_CONSTEXPR BPConfig::BPConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.item_list_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BPConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BPConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BPConfigDefaultTypeInternal() {}
  union {
    BPConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BPConfigDefaultTypeInternal _BPConfig_default_instance_;
}  // namespace pb
static ::_pb::Metadata file_level_metadata_DataConfig_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_DataConfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_DataConfig_2eproto = nullptr;

const uint32_t TableStruct_DataConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig_UIItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig_UIItem, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig_UIItem, _impl_.layer_),
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig_UIItem, _impl_.layout_),
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig_UIItem, _impl_.script_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::GuiConfig, _impl_.item_list_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::BPConfig_BPItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::BPConfig_BPItem, _impl_.bp_name_),
  PROTOBUF_FIELD_OFFSET(::pb::BPConfig_BPItem, _impl_.lua_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::BPConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::BPConfig, _impl_.item_list_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pb::GuiConfig_UIItem)},
  { 10, -1, -1, sizeof(::pb::GuiConfig)},
  { 17, -1, -1, sizeof(::pb::BPConfig_BPItem)},
  { 25, -1, -1, sizeof(::pb::BPConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pb::_GuiConfig_UIItem_default_instance_._instance,
  &::pb::_GuiConfig_default_instance_._instance,
  &::pb::_BPConfig_BPItem_default_instance_._instance,
  &::pb::_BPConfig_default_instance_._instance,
};

const char descriptor_table_protodef_DataConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020DataConfig.proto\022\002pb\"y\n\tGuiConfig\022\'\n\ti"
  "tem_list\030\001 \003(\0132\024.pb.GuiConfig.UIItem\032C\n\006"
  "UIItem\022\n\n\002id\030\001 \001(\005\022\r\n\005layer\030\002 \001(\005\022\016\n\006lay"
  "out\030\003 \001(\t\022\016\n\006script\030\004 \001(\t\"_\n\010BPConfig\022&\n"
  "\titem_list\030\001 \003(\0132\023.pb.BPConfig.BPItem\032+\n"
  "\006BPItem\022\017\n\007bp_name\030\001 \001(\t\022\020\n\010lua_name\030\002 \001"
  "(\tB\002H\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_DataConfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DataConfig_2eproto = {
    false, false, 254, descriptor_table_protodef_DataConfig_2eproto,
    "DataConfig.proto",
    &descriptor_table_DataConfig_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_DataConfig_2eproto::offsets,
    file_level_metadata_DataConfig_2eproto, file_level_enum_descriptors_DataConfig_2eproto,
    file_level_service_descriptors_DataConfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DataConfig_2eproto_getter() {
  return &descriptor_table_DataConfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DataConfig_2eproto(&descriptor_table_DataConfig_2eproto);
namespace pb {

// ===================================================================

class GuiConfig_UIItem::_Internal {
 public:
};

GuiConfig_UIItem::GuiConfig_UIItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.GuiConfig.UIItem)
}
GuiConfig_UIItem::GuiConfig_UIItem(const GuiConfig_UIItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GuiConfig_UIItem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.layout_){}
    , decltype(_impl_.script_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.layer_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.layout_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layout_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_layout().empty()) {
    _this->_impl_.layout_.Set(from._internal_layout(), 
      _this->GetArenaForAllocation());
  }
  _impl_.script_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.script_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_script().empty()) {
    _this->_impl_.script_.Set(from._internal_script(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.layer_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.layer_));
  // @@protoc_insertion_point(copy_constructor:pb.GuiConfig.UIItem)
}

inline void GuiConfig_UIItem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.layout_){}
    , decltype(_impl_.script_){}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.layer_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.layout_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.layout_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.script_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.script_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GuiConfig_UIItem::~GuiConfig_UIItem() {
  // @@protoc_insertion_point(destructor:pb.GuiConfig.UIItem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GuiConfig_UIItem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.layout_.Destroy();
  _impl_.script_.Destroy();
}

void GuiConfig_UIItem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GuiConfig_UIItem::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.GuiConfig.UIItem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.layout_.ClearToEmpty();
  _impl_.script_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.layer_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.layer_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GuiConfig_UIItem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 layer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.layer_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string layout = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_layout();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.GuiConfig.UIItem.layout"));
        } else
          goto handle_unusual;
        continue;
      // string script = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_script();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.GuiConfig.UIItem.script"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GuiConfig_UIItem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.GuiConfig.UIItem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // int32 layer = 2;
  if (this->_internal_layer() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_layer(), target);
  }

  // string layout = 3;
  if (!this->_internal_layout().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_layout().data(), static_cast<int>(this->_internal_layout().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.GuiConfig.UIItem.layout");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_layout(), target);
  }

  // string script = 4;
  if (!this->_internal_script().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_script().data(), static_cast<int>(this->_internal_script().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.GuiConfig.UIItem.script");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_script(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.GuiConfig.UIItem)
  return target;
}

size_t GuiConfig_UIItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.GuiConfig.UIItem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string layout = 3;
  if (!this->_internal_layout().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_layout());
  }

  // string script = 4;
  if (!this->_internal_script().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_script());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 layer = 2;
  if (this->_internal_layer() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_layer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GuiConfig_UIItem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GuiConfig_UIItem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GuiConfig_UIItem::GetClassData() const { return &_class_data_; }


void GuiConfig_UIItem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GuiConfig_UIItem*>(&to_msg);
  auto& from = static_cast<const GuiConfig_UIItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.GuiConfig.UIItem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_layout().empty()) {
    _this->_internal_set_layout(from._internal_layout());
  }
  if (!from._internal_script().empty()) {
    _this->_internal_set_script(from._internal_script());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_layer() != 0) {
    _this->_internal_set_layer(from._internal_layer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GuiConfig_UIItem::CopyFrom(const GuiConfig_UIItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.GuiConfig.UIItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GuiConfig_UIItem::IsInitialized() const {
  return true;
}

void GuiConfig_UIItem::InternalSwap(GuiConfig_UIItem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.layout_, lhs_arena,
      &other->_impl_.layout_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.script_, lhs_arena,
      &other->_impl_.script_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GuiConfig_UIItem, _impl_.layer_)
      + sizeof(GuiConfig_UIItem::_impl_.layer_)
      - PROTOBUF_FIELD_OFFSET(GuiConfig_UIItem, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GuiConfig_UIItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DataConfig_2eproto_getter, &descriptor_table_DataConfig_2eproto_once,
      file_level_metadata_DataConfig_2eproto[0]);
}

// ===================================================================

class GuiConfig::_Internal {
 public:
};

GuiConfig::GuiConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.GuiConfig)
}
GuiConfig::GuiConfig(const GuiConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GuiConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.item_list_){from._impl_.item_list_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.GuiConfig)
}

inline void GuiConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.item_list_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GuiConfig::~GuiConfig() {
  // @@protoc_insertion_point(destructor:pb.GuiConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GuiConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.item_list_.~RepeatedPtrField();
}

void GuiConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GuiConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.GuiConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.item_list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GuiConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .pb.GuiConfig.UIItem item_list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_item_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GuiConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.GuiConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.GuiConfig.UIItem item_list = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_item_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_item_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.GuiConfig)
  return target;
}

size_t GuiConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.GuiConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.GuiConfig.UIItem item_list = 1;
  total_size += 1UL * this->_internal_item_list_size();
  for (const auto& msg : this->_impl_.item_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GuiConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GuiConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GuiConfig::GetClassData() const { return &_class_data_; }


void GuiConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GuiConfig*>(&to_msg);
  auto& from = static_cast<const GuiConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.GuiConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.item_list_.MergeFrom(from._impl_.item_list_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GuiConfig::CopyFrom(const GuiConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.GuiConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GuiConfig::IsInitialized() const {
  return true;
}

void GuiConfig::InternalSwap(GuiConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.item_list_.InternalSwap(&other->_impl_.item_list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GuiConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DataConfig_2eproto_getter, &descriptor_table_DataConfig_2eproto_once,
      file_level_metadata_DataConfig_2eproto[1]);
}

// ===================================================================

class BPConfig_BPItem::_Internal {
 public:
};

BPConfig_BPItem::BPConfig_BPItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.BPConfig.BPItem)
}
BPConfig_BPItem::BPConfig_BPItem(const BPConfig_BPItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BPConfig_BPItem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bp_name_){}
    , decltype(_impl_.lua_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.bp_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bp_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bp_name().empty()) {
    _this->_impl_.bp_name_.Set(from._internal_bp_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lua_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lua_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lua_name().empty()) {
    _this->_impl_.lua_name_.Set(from._internal_lua_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:pb.BPConfig.BPItem)
}

inline void BPConfig_BPItem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bp_name_){}
    , decltype(_impl_.lua_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.bp_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bp_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lua_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lua_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BPConfig_BPItem::~BPConfig_BPItem() {
  // @@protoc_insertion_point(destructor:pb.BPConfig.BPItem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BPConfig_BPItem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bp_name_.Destroy();
  _impl_.lua_name_.Destroy();
}

void BPConfig_BPItem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BPConfig_BPItem::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.BPConfig.BPItem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bp_name_.ClearToEmpty();
  _impl_.lua_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BPConfig_BPItem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string bp_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_bp_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.BPConfig.BPItem.bp_name"));
        } else
          goto handle_unusual;
        continue;
      // string lua_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_lua_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.BPConfig.BPItem.lua_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BPConfig_BPItem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.BPConfig.BPItem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string bp_name = 1;
  if (!this->_internal_bp_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_bp_name().data(), static_cast<int>(this->_internal_bp_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.BPConfig.BPItem.bp_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_bp_name(), target);
  }

  // string lua_name = 2;
  if (!this->_internal_lua_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lua_name().data(), static_cast<int>(this->_internal_lua_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.BPConfig.BPItem.lua_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_lua_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.BPConfig.BPItem)
  return target;
}

size_t BPConfig_BPItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.BPConfig.BPItem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string bp_name = 1;
  if (!this->_internal_bp_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bp_name());
  }

  // string lua_name = 2;
  if (!this->_internal_lua_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lua_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BPConfig_BPItem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BPConfig_BPItem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BPConfig_BPItem::GetClassData() const { return &_class_data_; }


void BPConfig_BPItem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BPConfig_BPItem*>(&to_msg);
  auto& from = static_cast<const BPConfig_BPItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.BPConfig.BPItem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_bp_name().empty()) {
    _this->_internal_set_bp_name(from._internal_bp_name());
  }
  if (!from._internal_lua_name().empty()) {
    _this->_internal_set_lua_name(from._internal_lua_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BPConfig_BPItem::CopyFrom(const BPConfig_BPItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.BPConfig.BPItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BPConfig_BPItem::IsInitialized() const {
  return true;
}

void BPConfig_BPItem::InternalSwap(BPConfig_BPItem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bp_name_, lhs_arena,
      &other->_impl_.bp_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lua_name_, lhs_arena,
      &other->_impl_.lua_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BPConfig_BPItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DataConfig_2eproto_getter, &descriptor_table_DataConfig_2eproto_once,
      file_level_metadata_DataConfig_2eproto[2]);
}

// ===================================================================

class BPConfig::_Internal {
 public:
};

BPConfig::BPConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.BPConfig)
}
BPConfig::BPConfig(const BPConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BPConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.item_list_){from._impl_.item_list_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.BPConfig)
}

inline void BPConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.item_list_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BPConfig::~BPConfig() {
  // @@protoc_insertion_point(destructor:pb.BPConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BPConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.item_list_.~RepeatedPtrField();
}

void BPConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BPConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.BPConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.item_list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BPConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .pb.BPConfig.BPItem item_list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_item_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BPConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.BPConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.BPConfig.BPItem item_list = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_item_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_item_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.BPConfig)
  return target;
}

size_t BPConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.BPConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.BPConfig.BPItem item_list = 1;
  total_size += 1UL * this->_internal_item_list_size();
  for (const auto& msg : this->_impl_.item_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BPConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BPConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BPConfig::GetClassData() const { return &_class_data_; }


void BPConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BPConfig*>(&to_msg);
  auto& from = static_cast<const BPConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.BPConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.item_list_.MergeFrom(from._impl_.item_list_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BPConfig::CopyFrom(const BPConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.BPConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BPConfig::IsInitialized() const {
  return true;
}

void BPConfig::InternalSwap(BPConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.item_list_.InternalSwap(&other->_impl_.item_list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BPConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DataConfig_2eproto_getter, &descriptor_table_DataConfig_2eproto_once,
      file_level_metadata_DataConfig_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::GuiConfig_UIItem*
Arena::CreateMaybeMessage< ::pb::GuiConfig_UIItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::GuiConfig_UIItem >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::GuiConfig*
Arena::CreateMaybeMessage< ::pb::GuiConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::GuiConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::BPConfig_BPItem*
Arena::CreateMaybeMessage< ::pb::BPConfig_BPItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::BPConfig_BPItem >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::BPConfig*
Arena::CreateMaybeMessage< ::pb::BPConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::BPConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
