// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DataConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DataConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DataConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DataConfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DataConfig_2eproto;
namespace pb {
class BPConfig;
struct BPConfigDefaultTypeInternal;
extern BPConfigDefaultTypeInternal _BPConfig_default_instance_;
class BPConfig_BPItem;
struct BPConfig_BPItemDefaultTypeInternal;
extern BPConfig_BPItemDefaultTypeInternal _BPConfig_BPItem_default_instance_;
class GuiConfig;
struct GuiConfigDefaultTypeInternal;
extern GuiConfigDefaultTypeInternal _GuiConfig_default_instance_;
class GuiConfig_ItemMapEntry_DoNotUse;
struct GuiConfig_ItemMapEntry_DoNotUseDefaultTypeInternal;
extern GuiConfig_ItemMapEntry_DoNotUseDefaultTypeInternal _GuiConfig_ItemMapEntry_DoNotUse_default_instance_;
class GuiConfig_UIItem;
struct GuiConfig_UIItemDefaultTypeInternal;
extern GuiConfig_UIItemDefaultTypeInternal _GuiConfig_UIItem_default_instance_;
class Result;
struct ResultDefaultTypeInternal;
extern ResultDefaultTypeInternal _Result_default_instance_;
class TestConfig;
struct TestConfigDefaultTypeInternal;
extern TestConfigDefaultTypeInternal _TestConfig_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::BPConfig* Arena::CreateMaybeMessage<::pb::BPConfig>(Arena*);
template<> ::pb::BPConfig_BPItem* Arena::CreateMaybeMessage<::pb::BPConfig_BPItem>(Arena*);
template<> ::pb::GuiConfig* Arena::CreateMaybeMessage<::pb::GuiConfig>(Arena*);
template<> ::pb::GuiConfig_ItemMapEntry_DoNotUse* Arena::CreateMaybeMessage<::pb::GuiConfig_ItemMapEntry_DoNotUse>(Arena*);
template<> ::pb::GuiConfig_UIItem* Arena::CreateMaybeMessage<::pb::GuiConfig_UIItem>(Arena*);
template<> ::pb::Result* Arena::CreateMaybeMessage<::pb::Result>(Arena*);
template<> ::pb::TestConfig* Arena::CreateMaybeMessage<::pb::TestConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class GuiConfig_UIItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.GuiConfig.UIItem) */ {
 public:
  inline GuiConfig_UIItem() : GuiConfig_UIItem(nullptr) {}
  ~GuiConfig_UIItem() override;
  explicit PROTOBUF_CONSTEXPR GuiConfig_UIItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GuiConfig_UIItem(const GuiConfig_UIItem& from);
  GuiConfig_UIItem(GuiConfig_UIItem&& from) noexcept
    : GuiConfig_UIItem() {
    *this = ::std::move(from);
  }

  inline GuiConfig_UIItem& operator=(const GuiConfig_UIItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuiConfig_UIItem& operator=(GuiConfig_UIItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuiConfig_UIItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const GuiConfig_UIItem* internal_default_instance() {
    return reinterpret_cast<const GuiConfig_UIItem*>(
               &_GuiConfig_UIItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GuiConfig_UIItem& a, GuiConfig_UIItem& b) {
    a.Swap(&b);
  }
  inline void Swap(GuiConfig_UIItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuiConfig_UIItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuiConfig_UIItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GuiConfig_UIItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GuiConfig_UIItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GuiConfig_UIItem& from) {
    GuiConfig_UIItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GuiConfig_UIItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.GuiConfig.UIItem";
  }
  protected:
  explicit GuiConfig_UIItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLayoutFieldNumber = 3,
    kIdFieldNumber = 1,
    kLayerFieldNumber = 4,
  };
  // string layout = 3;
  void clear_layout();
  const std::string& layout() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_layout(ArgT0&& arg0, ArgT... args);
  std::string* mutable_layout();
  PROTOBUF_NODISCARD std::string* release_layout();
  void set_allocated_layout(std::string* layout);
  private:
  const std::string& _internal_layout() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_layout(const std::string& value);
  std::string* _internal_mutable_layout();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 layer = 4;
  void clear_layer();
  int32_t layer() const;
  void set_layer(int32_t value);
  private:
  int32_t _internal_layer() const;
  void _internal_set_layer(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.GuiConfig.UIItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr layout_;
    int32_t id_;
    int32_t layer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// -------------------------------------------------------------------

class GuiConfig_ItemMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GuiConfig_ItemMapEntry_DoNotUse, 
    std::string, ::pb::GuiConfig_UIItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GuiConfig_ItemMapEntry_DoNotUse, 
    std::string, ::pb::GuiConfig_UIItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  GuiConfig_ItemMapEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR GuiConfig_ItemMapEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit GuiConfig_ItemMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const GuiConfig_ItemMapEntry_DoNotUse& other);
  static const GuiConfig_ItemMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GuiConfig_ItemMapEntry_DoNotUse*>(&_GuiConfig_ItemMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "pb.GuiConfig.ItemMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_DataConfig_2eproto;
};

// -------------------------------------------------------------------

class GuiConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.GuiConfig) */ {
 public:
  inline GuiConfig() : GuiConfig(nullptr) {}
  ~GuiConfig() override;
  explicit PROTOBUF_CONSTEXPR GuiConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GuiConfig(const GuiConfig& from);
  GuiConfig(GuiConfig&& from) noexcept
    : GuiConfig() {
    *this = ::std::move(from);
  }

  inline GuiConfig& operator=(const GuiConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuiConfig& operator=(GuiConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuiConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const GuiConfig* internal_default_instance() {
    return reinterpret_cast<const GuiConfig*>(
               &_GuiConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GuiConfig& a, GuiConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(GuiConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuiConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuiConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GuiConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GuiConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GuiConfig& from) {
    GuiConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GuiConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.GuiConfig";
  }
  protected:
  explicit GuiConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GuiConfig_UIItem UIItem;

  // accessors -------------------------------------------------------

  enum : int {
    kItemMapFieldNumber = 1,
  };
  // map<string, .pb.GuiConfig.UIItem> item_map = 1;
  int item_map_size() const;
  private:
  int _internal_item_map_size() const;
  public:
  void clear_item_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >&
      _internal_item_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >*
      _internal_mutable_item_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >&
      item_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >*
      mutable_item_map();

  // @@protoc_insertion_point(class_scope:pb.GuiConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        GuiConfig_ItemMapEntry_DoNotUse,
        std::string, ::pb::GuiConfig_UIItem,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> item_map_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// -------------------------------------------------------------------

class BPConfig_BPItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.BPConfig.BPItem) */ {
 public:
  inline BPConfig_BPItem() : BPConfig_BPItem(nullptr) {}
  ~BPConfig_BPItem() override;
  explicit PROTOBUF_CONSTEXPR BPConfig_BPItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BPConfig_BPItem(const BPConfig_BPItem& from);
  BPConfig_BPItem(BPConfig_BPItem&& from) noexcept
    : BPConfig_BPItem() {
    *this = ::std::move(from);
  }

  inline BPConfig_BPItem& operator=(const BPConfig_BPItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline BPConfig_BPItem& operator=(BPConfig_BPItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BPConfig_BPItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const BPConfig_BPItem* internal_default_instance() {
    return reinterpret_cast<const BPConfig_BPItem*>(
               &_BPConfig_BPItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BPConfig_BPItem& a, BPConfig_BPItem& b) {
    a.Swap(&b);
  }
  inline void Swap(BPConfig_BPItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BPConfig_BPItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BPConfig_BPItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BPConfig_BPItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BPConfig_BPItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BPConfig_BPItem& from) {
    BPConfig_BPItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BPConfig_BPItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.BPConfig.BPItem";
  }
  protected:
  explicit BPConfig_BPItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBpNameFieldNumber = 1,
    kLuaNameFieldNumber = 2,
  };
  // string bp_name = 1;
  void clear_bp_name();
  const std::string& bp_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bp_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bp_name();
  PROTOBUF_NODISCARD std::string* release_bp_name();
  void set_allocated_bp_name(std::string* bp_name);
  private:
  const std::string& _internal_bp_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bp_name(const std::string& value);
  std::string* _internal_mutable_bp_name();
  public:

  // string lua_name = 2;
  void clear_lua_name();
  const std::string& lua_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lua_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lua_name();
  PROTOBUF_NODISCARD std::string* release_lua_name();
  void set_allocated_lua_name(std::string* lua_name);
  private:
  const std::string& _internal_lua_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lua_name(const std::string& value);
  std::string* _internal_mutable_lua_name();
  public:

  // @@protoc_insertion_point(class_scope:pb.BPConfig.BPItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bp_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lua_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// -------------------------------------------------------------------

class BPConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.BPConfig) */ {
 public:
  inline BPConfig() : BPConfig(nullptr) {}
  ~BPConfig() override;
  explicit PROTOBUF_CONSTEXPR BPConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BPConfig(const BPConfig& from);
  BPConfig(BPConfig&& from) noexcept
    : BPConfig() {
    *this = ::std::move(from);
  }

  inline BPConfig& operator=(const BPConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline BPConfig& operator=(BPConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BPConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const BPConfig* internal_default_instance() {
    return reinterpret_cast<const BPConfig*>(
               &_BPConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(BPConfig& a, BPConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(BPConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BPConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BPConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BPConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BPConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BPConfig& from) {
    BPConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BPConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.BPConfig";
  }
  protected:
  explicit BPConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BPConfig_BPItem BPItem;

  // accessors -------------------------------------------------------

  enum : int {
    kItemListFieldNumber = 1,
  };
  // repeated .pb.BPConfig.BPItem item_list = 1;
  int item_list_size() const;
  private:
  int _internal_item_list_size() const;
  public:
  void clear_item_list();
  ::pb::BPConfig_BPItem* mutable_item_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::BPConfig_BPItem >*
      mutable_item_list();
  private:
  const ::pb::BPConfig_BPItem& _internal_item_list(int index) const;
  ::pb::BPConfig_BPItem* _internal_add_item_list();
  public:
  const ::pb::BPConfig_BPItem& item_list(int index) const;
  ::pb::BPConfig_BPItem* add_item_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::BPConfig_BPItem >&
      item_list() const;

  // @@protoc_insertion_point(class_scope:pb.BPConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::BPConfig_BPItem > item_list_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// -------------------------------------------------------------------

class Result final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.Result) */ {
 public:
  inline Result() : Result(nullptr) {}
  ~Result() override;
  explicit PROTOBUF_CONSTEXPR Result(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Result(const Result& from);
  Result(Result&& from) noexcept
    : Result() {
    *this = ::std::move(from);
  }

  inline Result& operator=(const Result& from) {
    CopyFrom(from);
    return *this;
  }
  inline Result& operator=(Result&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Result& default_instance() {
    return *internal_default_instance();
  }
  static inline const Result* internal_default_instance() {
    return reinterpret_cast<const Result*>(
               &_Result_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Result& a, Result& b) {
    a.Swap(&b);
  }
  inline void Swap(Result* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Result* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Result* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Result>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Result& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Result& from) {
    Result::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Result* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.Result";
  }
  protected:
  explicit Result(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBpNameFieldNumber = 1,
    kLuaNameFieldNumber = 2,
  };
  // string bp_name = 1;
  void clear_bp_name();
  const std::string& bp_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bp_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bp_name();
  PROTOBUF_NODISCARD std::string* release_bp_name();
  void set_allocated_bp_name(std::string* bp_name);
  private:
  const std::string& _internal_bp_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bp_name(const std::string& value);
  std::string* _internal_mutable_bp_name();
  public:

  // string lua_name = 2;
  void clear_lua_name();
  const std::string& lua_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lua_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lua_name();
  PROTOBUF_NODISCARD std::string* release_lua_name();
  void set_allocated_lua_name(std::string* lua_name);
  private:
  const std::string& _internal_lua_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lua_name(const std::string& value);
  std::string* _internal_mutable_lua_name();
  public:

  // @@protoc_insertion_point(class_scope:pb.Result)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bp_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lua_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// -------------------------------------------------------------------

class TestConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.TestConfig) */ {
 public:
  inline TestConfig() : TestConfig(nullptr) {}
  ~TestConfig() override;
  explicit PROTOBUF_CONSTEXPR TestConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestConfig(const TestConfig& from);
  TestConfig(TestConfig&& from) noexcept
    : TestConfig() {
    *this = ::std::move(from);
  }

  inline TestConfig& operator=(const TestConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestConfig& operator=(TestConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestConfig* internal_default_instance() {
    return reinterpret_cast<const TestConfig*>(
               &_TestConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(TestConfig& a, TestConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(TestConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TestConfig& from) {
    TestConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.TestConfig";
  }
  protected:
  explicit TestConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBFieldNumber = 2,
    kDFieldNumber = 4,
    kCFieldNumber = 3,
    kAFieldNumber = 1,
  };
  // repeated string b = 2;
  int b_size() const;
  private:
  int _internal_b_size() const;
  public:
  void clear_b();
  const std::string& b(int index) const;
  std::string* mutable_b(int index);
  void set_b(int index, const std::string& value);
  void set_b(int index, std::string&& value);
  void set_b(int index, const char* value);
  void set_b(int index, const char* value, size_t size);
  std::string* add_b();
  void add_b(const std::string& value);
  void add_b(std::string&& value);
  void add_b(const char* value);
  void add_b(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& b() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_b();
  private:
  const std::string& _internal_b(int index) const;
  std::string* _internal_add_b();
  public:

  // repeated .pb.Result d = 4;
  int d_size() const;
  private:
  int _internal_d_size() const;
  public:
  void clear_d();
  ::pb::Result* mutable_d(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::Result >*
      mutable_d();
  private:
  const ::pb::Result& _internal_d(int index) const;
  ::pb::Result* _internal_add_d();
  public:
  const ::pb::Result& d(int index) const;
  ::pb::Result* add_d();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::Result >&
      d() const;

  // string c = 3;
  void clear_c();
  const std::string& c() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_c(ArgT0&& arg0, ArgT... args);
  std::string* mutable_c();
  PROTOBUF_NODISCARD std::string* release_c();
  void set_allocated_c(std::string* c);
  private:
  const std::string& _internal_c() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_c(const std::string& value);
  std::string* _internal_mutable_c();
  public:

  // int32 a = 1;
  void clear_a();
  int32_t a() const;
  void set_a(int32_t value);
  private:
  int32_t _internal_a() const;
  void _internal_set_a(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.TestConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> b_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::Result > d_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr c_;
    int32_t a_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DataConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GuiConfig_UIItem

// int32 id = 1;
inline void GuiConfig_UIItem::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t GuiConfig_UIItem::_internal_id() const {
  return _impl_.id_;
}
inline int32_t GuiConfig_UIItem::id() const {
  // @@protoc_insertion_point(field_get:pb.GuiConfig.UIItem.id)
  return _internal_id();
}
inline void GuiConfig_UIItem::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void GuiConfig_UIItem::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:pb.GuiConfig.UIItem.id)
}

// string layout = 3;
inline void GuiConfig_UIItem::clear_layout() {
  _impl_.layout_.ClearToEmpty();
}
inline const std::string& GuiConfig_UIItem::layout() const {
  // @@protoc_insertion_point(field_get:pb.GuiConfig.UIItem.layout)
  return _internal_layout();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GuiConfig_UIItem::set_layout(ArgT0&& arg0, ArgT... args) {
 
 _impl_.layout_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.GuiConfig.UIItem.layout)
}
inline std::string* GuiConfig_UIItem::mutable_layout() {
  std::string* _s = _internal_mutable_layout();
  // @@protoc_insertion_point(field_mutable:pb.GuiConfig.UIItem.layout)
  return _s;
}
inline const std::string& GuiConfig_UIItem::_internal_layout() const {
  return _impl_.layout_.Get();
}
inline void GuiConfig_UIItem::_internal_set_layout(const std::string& value) {
  
  _impl_.layout_.Set(value, GetArenaForAllocation());
}
inline std::string* GuiConfig_UIItem::_internal_mutable_layout() {
  
  return _impl_.layout_.Mutable(GetArenaForAllocation());
}
inline std::string* GuiConfig_UIItem::release_layout() {
  // @@protoc_insertion_point(field_release:pb.GuiConfig.UIItem.layout)
  return _impl_.layout_.Release();
}
inline void GuiConfig_UIItem::set_allocated_layout(std::string* layout) {
  if (layout != nullptr) {
    
  } else {
    
  }
  _impl_.layout_.SetAllocated(layout, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.layout_.IsDefault()) {
    _impl_.layout_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.GuiConfig.UIItem.layout)
}

// int32 layer = 4;
inline void GuiConfig_UIItem::clear_layer() {
  _impl_.layer_ = 0;
}
inline int32_t GuiConfig_UIItem::_internal_layer() const {
  return _impl_.layer_;
}
inline int32_t GuiConfig_UIItem::layer() const {
  // @@protoc_insertion_point(field_get:pb.GuiConfig.UIItem.layer)
  return _internal_layer();
}
inline void GuiConfig_UIItem::_internal_set_layer(int32_t value) {
  
  _impl_.layer_ = value;
}
inline void GuiConfig_UIItem::set_layer(int32_t value) {
  _internal_set_layer(value);
  // @@protoc_insertion_point(field_set:pb.GuiConfig.UIItem.layer)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GuiConfig

// map<string, .pb.GuiConfig.UIItem> item_map = 1;
inline int GuiConfig::_internal_item_map_size() const {
  return _impl_.item_map_.size();
}
inline int GuiConfig::item_map_size() const {
  return _internal_item_map_size();
}
inline void GuiConfig::clear_item_map() {
  _impl_.item_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >&
GuiConfig::_internal_item_map() const {
  return _impl_.item_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >&
GuiConfig::item_map() const {
  // @@protoc_insertion_point(field_map:pb.GuiConfig.item_map)
  return _internal_item_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >*
GuiConfig::_internal_mutable_item_map() {
  return _impl_.item_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::pb::GuiConfig_UIItem >*
GuiConfig::mutable_item_map() {
  // @@protoc_insertion_point(field_mutable_map:pb.GuiConfig.item_map)
  return _internal_mutable_item_map();
}

// -------------------------------------------------------------------

// BPConfig_BPItem

// string bp_name = 1;
inline void BPConfig_BPItem::clear_bp_name() {
  _impl_.bp_name_.ClearToEmpty();
}
inline const std::string& BPConfig_BPItem::bp_name() const {
  // @@protoc_insertion_point(field_get:pb.BPConfig.BPItem.bp_name)
  return _internal_bp_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BPConfig_BPItem::set_bp_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bp_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.BPConfig.BPItem.bp_name)
}
inline std::string* BPConfig_BPItem::mutable_bp_name() {
  std::string* _s = _internal_mutable_bp_name();
  // @@protoc_insertion_point(field_mutable:pb.BPConfig.BPItem.bp_name)
  return _s;
}
inline const std::string& BPConfig_BPItem::_internal_bp_name() const {
  return _impl_.bp_name_.Get();
}
inline void BPConfig_BPItem::_internal_set_bp_name(const std::string& value) {
  
  _impl_.bp_name_.Set(value, GetArenaForAllocation());
}
inline std::string* BPConfig_BPItem::_internal_mutable_bp_name() {
  
  return _impl_.bp_name_.Mutable(GetArenaForAllocation());
}
inline std::string* BPConfig_BPItem::release_bp_name() {
  // @@protoc_insertion_point(field_release:pb.BPConfig.BPItem.bp_name)
  return _impl_.bp_name_.Release();
}
inline void BPConfig_BPItem::set_allocated_bp_name(std::string* bp_name) {
  if (bp_name != nullptr) {
    
  } else {
    
  }
  _impl_.bp_name_.SetAllocated(bp_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bp_name_.IsDefault()) {
    _impl_.bp_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.BPConfig.BPItem.bp_name)
}

// string lua_name = 2;
inline void BPConfig_BPItem::clear_lua_name() {
  _impl_.lua_name_.ClearToEmpty();
}
inline const std::string& BPConfig_BPItem::lua_name() const {
  // @@protoc_insertion_point(field_get:pb.BPConfig.BPItem.lua_name)
  return _internal_lua_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BPConfig_BPItem::set_lua_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.lua_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.BPConfig.BPItem.lua_name)
}
inline std::string* BPConfig_BPItem::mutable_lua_name() {
  std::string* _s = _internal_mutable_lua_name();
  // @@protoc_insertion_point(field_mutable:pb.BPConfig.BPItem.lua_name)
  return _s;
}
inline const std::string& BPConfig_BPItem::_internal_lua_name() const {
  return _impl_.lua_name_.Get();
}
inline void BPConfig_BPItem::_internal_set_lua_name(const std::string& value) {
  
  _impl_.lua_name_.Set(value, GetArenaForAllocation());
}
inline std::string* BPConfig_BPItem::_internal_mutable_lua_name() {
  
  return _impl_.lua_name_.Mutable(GetArenaForAllocation());
}
inline std::string* BPConfig_BPItem::release_lua_name() {
  // @@protoc_insertion_point(field_release:pb.BPConfig.BPItem.lua_name)
  return _impl_.lua_name_.Release();
}
inline void BPConfig_BPItem::set_allocated_lua_name(std::string* lua_name) {
  if (lua_name != nullptr) {
    
  } else {
    
  }
  _impl_.lua_name_.SetAllocated(lua_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lua_name_.IsDefault()) {
    _impl_.lua_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.BPConfig.BPItem.lua_name)
}

// -------------------------------------------------------------------

// BPConfig

// repeated .pb.BPConfig.BPItem item_list = 1;
inline int BPConfig::_internal_item_list_size() const {
  return _impl_.item_list_.size();
}
inline int BPConfig::item_list_size() const {
  return _internal_item_list_size();
}
inline void BPConfig::clear_item_list() {
  _impl_.item_list_.Clear();
}
inline ::pb::BPConfig_BPItem* BPConfig::mutable_item_list(int index) {
  // @@protoc_insertion_point(field_mutable:pb.BPConfig.item_list)
  return _impl_.item_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::BPConfig_BPItem >*
BPConfig::mutable_item_list() {
  // @@protoc_insertion_point(field_mutable_list:pb.BPConfig.item_list)
  return &_impl_.item_list_;
}
inline const ::pb::BPConfig_BPItem& BPConfig::_internal_item_list(int index) const {
  return _impl_.item_list_.Get(index);
}
inline const ::pb::BPConfig_BPItem& BPConfig::item_list(int index) const {
  // @@protoc_insertion_point(field_get:pb.BPConfig.item_list)
  return _internal_item_list(index);
}
inline ::pb::BPConfig_BPItem* BPConfig::_internal_add_item_list() {
  return _impl_.item_list_.Add();
}
inline ::pb::BPConfig_BPItem* BPConfig::add_item_list() {
  ::pb::BPConfig_BPItem* _add = _internal_add_item_list();
  // @@protoc_insertion_point(field_add:pb.BPConfig.item_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::BPConfig_BPItem >&
BPConfig::item_list() const {
  // @@protoc_insertion_point(field_list:pb.BPConfig.item_list)
  return _impl_.item_list_;
}

// -------------------------------------------------------------------

// Result

// string bp_name = 1;
inline void Result::clear_bp_name() {
  _impl_.bp_name_.ClearToEmpty();
}
inline const std::string& Result::bp_name() const {
  // @@protoc_insertion_point(field_get:pb.Result.bp_name)
  return _internal_bp_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Result::set_bp_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bp_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.Result.bp_name)
}
inline std::string* Result::mutable_bp_name() {
  std::string* _s = _internal_mutable_bp_name();
  // @@protoc_insertion_point(field_mutable:pb.Result.bp_name)
  return _s;
}
inline const std::string& Result::_internal_bp_name() const {
  return _impl_.bp_name_.Get();
}
inline void Result::_internal_set_bp_name(const std::string& value) {
  
  _impl_.bp_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Result::_internal_mutable_bp_name() {
  
  return _impl_.bp_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Result::release_bp_name() {
  // @@protoc_insertion_point(field_release:pb.Result.bp_name)
  return _impl_.bp_name_.Release();
}
inline void Result::set_allocated_bp_name(std::string* bp_name) {
  if (bp_name != nullptr) {
    
  } else {
    
  }
  _impl_.bp_name_.SetAllocated(bp_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bp_name_.IsDefault()) {
    _impl_.bp_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.Result.bp_name)
}

// string lua_name = 2;
inline void Result::clear_lua_name() {
  _impl_.lua_name_.ClearToEmpty();
}
inline const std::string& Result::lua_name() const {
  // @@protoc_insertion_point(field_get:pb.Result.lua_name)
  return _internal_lua_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Result::set_lua_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.lua_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.Result.lua_name)
}
inline std::string* Result::mutable_lua_name() {
  std::string* _s = _internal_mutable_lua_name();
  // @@protoc_insertion_point(field_mutable:pb.Result.lua_name)
  return _s;
}
inline const std::string& Result::_internal_lua_name() const {
  return _impl_.lua_name_.Get();
}
inline void Result::_internal_set_lua_name(const std::string& value) {
  
  _impl_.lua_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Result::_internal_mutable_lua_name() {
  
  return _impl_.lua_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Result::release_lua_name() {
  // @@protoc_insertion_point(field_release:pb.Result.lua_name)
  return _impl_.lua_name_.Release();
}
inline void Result::set_allocated_lua_name(std::string* lua_name) {
  if (lua_name != nullptr) {
    
  } else {
    
  }
  _impl_.lua_name_.SetAllocated(lua_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lua_name_.IsDefault()) {
    _impl_.lua_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.Result.lua_name)
}

// -------------------------------------------------------------------

// TestConfig

// int32 a = 1;
inline void TestConfig::clear_a() {
  _impl_.a_ = 0;
}
inline int32_t TestConfig::_internal_a() const {
  return _impl_.a_;
}
inline int32_t TestConfig::a() const {
  // @@protoc_insertion_point(field_get:pb.TestConfig.a)
  return _internal_a();
}
inline void TestConfig::_internal_set_a(int32_t value) {
  
  _impl_.a_ = value;
}
inline void TestConfig::set_a(int32_t value) {
  _internal_set_a(value);
  // @@protoc_insertion_point(field_set:pb.TestConfig.a)
}

// repeated string b = 2;
inline int TestConfig::_internal_b_size() const {
  return _impl_.b_.size();
}
inline int TestConfig::b_size() const {
  return _internal_b_size();
}
inline void TestConfig::clear_b() {
  _impl_.b_.Clear();
}
inline std::string* TestConfig::add_b() {
  std::string* _s = _internal_add_b();
  // @@protoc_insertion_point(field_add_mutable:pb.TestConfig.b)
  return _s;
}
inline const std::string& TestConfig::_internal_b(int index) const {
  return _impl_.b_.Get(index);
}
inline const std::string& TestConfig::b(int index) const {
  // @@protoc_insertion_point(field_get:pb.TestConfig.b)
  return _internal_b(index);
}
inline std::string* TestConfig::mutable_b(int index) {
  // @@protoc_insertion_point(field_mutable:pb.TestConfig.b)
  return _impl_.b_.Mutable(index);
}
inline void TestConfig::set_b(int index, const std::string& value) {
  _impl_.b_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:pb.TestConfig.b)
}
inline void TestConfig::set_b(int index, std::string&& value) {
  _impl_.b_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:pb.TestConfig.b)
}
inline void TestConfig::set_b(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.b_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pb.TestConfig.b)
}
inline void TestConfig::set_b(int index, const char* value, size_t size) {
  _impl_.b_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb.TestConfig.b)
}
inline std::string* TestConfig::_internal_add_b() {
  return _impl_.b_.Add();
}
inline void TestConfig::add_b(const std::string& value) {
  _impl_.b_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pb.TestConfig.b)
}
inline void TestConfig::add_b(std::string&& value) {
  _impl_.b_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:pb.TestConfig.b)
}
inline void TestConfig::add_b(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.b_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pb.TestConfig.b)
}
inline void TestConfig::add_b(const char* value, size_t size) {
  _impl_.b_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pb.TestConfig.b)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TestConfig::b() const {
  // @@protoc_insertion_point(field_list:pb.TestConfig.b)
  return _impl_.b_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TestConfig::mutable_b() {
  // @@protoc_insertion_point(field_mutable_list:pb.TestConfig.b)
  return &_impl_.b_;
}

// string c = 3;
inline void TestConfig::clear_c() {
  _impl_.c_.ClearToEmpty();
}
inline const std::string& TestConfig::c() const {
  // @@protoc_insertion_point(field_get:pb.TestConfig.c)
  return _internal_c();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestConfig::set_c(ArgT0&& arg0, ArgT... args) {
 
 _impl_.c_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.TestConfig.c)
}
inline std::string* TestConfig::mutable_c() {
  std::string* _s = _internal_mutable_c();
  // @@protoc_insertion_point(field_mutable:pb.TestConfig.c)
  return _s;
}
inline const std::string& TestConfig::_internal_c() const {
  return _impl_.c_.Get();
}
inline void TestConfig::_internal_set_c(const std::string& value) {
  
  _impl_.c_.Set(value, GetArenaForAllocation());
}
inline std::string* TestConfig::_internal_mutable_c() {
  
  return _impl_.c_.Mutable(GetArenaForAllocation());
}
inline std::string* TestConfig::release_c() {
  // @@protoc_insertion_point(field_release:pb.TestConfig.c)
  return _impl_.c_.Release();
}
inline void TestConfig::set_allocated_c(std::string* c) {
  if (c != nullptr) {
    
  } else {
    
  }
  _impl_.c_.SetAllocated(c, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.c_.IsDefault()) {
    _impl_.c_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.TestConfig.c)
}

// repeated .pb.Result d = 4;
inline int TestConfig::_internal_d_size() const {
  return _impl_.d_.size();
}
inline int TestConfig::d_size() const {
  return _internal_d_size();
}
inline void TestConfig::clear_d() {
  _impl_.d_.Clear();
}
inline ::pb::Result* TestConfig::mutable_d(int index) {
  // @@protoc_insertion_point(field_mutable:pb.TestConfig.d)
  return _impl_.d_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::Result >*
TestConfig::mutable_d() {
  // @@protoc_insertion_point(field_mutable_list:pb.TestConfig.d)
  return &_impl_.d_;
}
inline const ::pb::Result& TestConfig::_internal_d(int index) const {
  return _impl_.d_.Get(index);
}
inline const ::pb::Result& TestConfig::d(int index) const {
  // @@protoc_insertion_point(field_get:pb.TestConfig.d)
  return _internal_d(index);
}
inline ::pb::Result* TestConfig::_internal_add_d() {
  return _impl_.d_.Add();
}
inline ::pb::Result* TestConfig::add_d() {
  ::pb::Result* _add = _internal_add_d();
  // @@protoc_insertion_point(field_add:pb.TestConfig.d)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::Result >&
TestConfig::d() const {
  // @@protoc_insertion_point(field_list:pb.TestConfig.d)
  return _impl_.d_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DataConfig_2eproto
