// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wrap.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Wrap_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Wrap_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Wrap_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Wrap_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Wrap_2eproto;
namespace pb {
class WrapMessage;
struct WrapMessageDefaultTypeInternal;
extern WrapMessageDefaultTypeInternal _WrapMessage_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::WrapMessage* Arena::CreateMaybeMessage<::pb::WrapMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class WrapMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.WrapMessage) */ {
 public:
  inline WrapMessage() : WrapMessage(nullptr) {}
  ~WrapMessage() override;
  explicit PROTOBUF_CONSTEXPR WrapMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WrapMessage(const WrapMessage& from);
  WrapMessage(WrapMessage&& from) noexcept
    : WrapMessage() {
    *this = ::std::move(from);
  }

  inline WrapMessage& operator=(const WrapMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline WrapMessage& operator=(WrapMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WrapMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const WrapMessage* internal_default_instance() {
    return reinterpret_cast<const WrapMessage*>(
               &_WrapMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WrapMessage& a, WrapMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(WrapMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WrapMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WrapMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WrapMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WrapMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WrapMessage& from) {
    WrapMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WrapMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.WrapMessage";
  }
  protected:
  explicit WrapMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 1,
    kRequestFieldNumber = 2,
    kResponseFieldNumber = 3,
    kCodeFieldNumber = 4,
  };
  // bytes content = 1;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // int32 request = 2;
  void clear_request();
  int32_t request() const;
  void set_request(int32_t value);
  private:
  int32_t _internal_request() const;
  void _internal_set_request(int32_t value);
  public:

  // int32 response = 3;
  void clear_response();
  int32_t response() const;
  void set_response(int32_t value);
  private:
  int32_t _internal_response() const;
  void _internal_set_response(int32_t value);
  public:

  // int32 code = 4;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.WrapMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    int32_t request_;
    int32_t response_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Wrap_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WrapMessage

// bytes content = 1;
inline void WrapMessage::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& WrapMessage::content() const {
  // @@protoc_insertion_point(field_get:pb.WrapMessage.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WrapMessage::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.WrapMessage.content)
}
inline std::string* WrapMessage::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:pb.WrapMessage.content)
  return _s;
}
inline const std::string& WrapMessage::_internal_content() const {
  return _impl_.content_.Get();
}
inline void WrapMessage::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* WrapMessage::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* WrapMessage::release_content() {
  // @@protoc_insertion_point(field_release:pb.WrapMessage.content)
  return _impl_.content_.Release();
}
inline void WrapMessage::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.WrapMessage.content)
}

// int32 request = 2;
inline void WrapMessage::clear_request() {
  _impl_.request_ = 0;
}
inline int32_t WrapMessage::_internal_request() const {
  return _impl_.request_;
}
inline int32_t WrapMessage::request() const {
  // @@protoc_insertion_point(field_get:pb.WrapMessage.request)
  return _internal_request();
}
inline void WrapMessage::_internal_set_request(int32_t value) {
  
  _impl_.request_ = value;
}
inline void WrapMessage::set_request(int32_t value) {
  _internal_set_request(value);
  // @@protoc_insertion_point(field_set:pb.WrapMessage.request)
}

// int32 response = 3;
inline void WrapMessage::clear_response() {
  _impl_.response_ = 0;
}
inline int32_t WrapMessage::_internal_response() const {
  return _impl_.response_;
}
inline int32_t WrapMessage::response() const {
  // @@protoc_insertion_point(field_get:pb.WrapMessage.response)
  return _internal_response();
}
inline void WrapMessage::_internal_set_response(int32_t value) {
  
  _impl_.response_ = value;
}
inline void WrapMessage::set_response(int32_t value) {
  _internal_set_response(value);
  // @@protoc_insertion_point(field_set:pb.WrapMessage.response)
}

// int32 code = 4;
inline void WrapMessage::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t WrapMessage::_internal_code() const {
  return _impl_.code_;
}
inline int32_t WrapMessage::code() const {
  // @@protoc_insertion_point(field_get:pb.WrapMessage.code)
  return _internal_code();
}
inline void WrapMessage::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void WrapMessage::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:pb.WrapMessage.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Wrap_2eproto
