# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  serialized_pb=b'\n\rMessage.proto\x12\x02pb\"c\n\x14\x41\x44\x44_ENGINE_COMPONENT\x12\x13\n\x0blisten_addr\x18\x01 \x01(\t\x12\x14\n\x0c\x63omponent_id\x18\x02 \x01(\r\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.pb.COMPONENT_TYPE\">\n\x18\x41\x44\x44_ENGINE_COMPONENT_ACK\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x14\n\x0c\x63omponent_id\x18\x02 \x01(\r\"M\n\x19\x41\x44\x44_ENGINE_COMPONENT_LIST\x12\x30\n\x0e\x63omponent_list\x18\x01 \x03(\x0b\x32\x18.pb.ADD_ENGINE_COMPONENT*K\n\x0e\x43OMPONENT_TYPE\x12\n\n\x06\x43\x45NTER\x10\x00\x12\x0e\n\nDISPATCHER\x10\x01\x12\t\n\x05LOGIN\x10\x02\x12\x08\n\x04GATE\x10\x03\x12\x08\n\x04GAME\x10\x04\x42\x06Z\x04.;pbb\x06proto3'
)

_COMPONENT_TYPE = _descriptor.EnumDescriptor(
  name='COMPONENT_TYPE',
  full_name='pb.COMPONENT_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CENTER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISPATCHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=265,
  serialized_end=340,
)
_sym_db.RegisterEnumDescriptor(_COMPONENT_TYPE)

COMPONENT_TYPE = enum_type_wrapper.EnumTypeWrapper(_COMPONENT_TYPE)
CENTER = 0
DISPATCHER = 1
LOGIN = 2
GATE = 3
GAME = 4



_ADD_ENGINE_COMPONENT = _descriptor.Descriptor(
  name='ADD_ENGINE_COMPONENT',
  full_name='pb.ADD_ENGINE_COMPONENT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listen_addr', full_name='pb.ADD_ENGINE_COMPONENT.listen_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='component_id', full_name='pb.ADD_ENGINE_COMPONENT.component_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.ADD_ENGINE_COMPONENT.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=120,
)


_ADD_ENGINE_COMPONENT_ACK = _descriptor.Descriptor(
  name='ADD_ENGINE_COMPONENT_ACK',
  full_name='pb.ADD_ENGINE_COMPONENT_ACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.ADD_ENGINE_COMPONENT_ACK.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='component_id', full_name='pb.ADD_ENGINE_COMPONENT_ACK.component_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=184,
)


_ADD_ENGINE_COMPONENT_LIST = _descriptor.Descriptor(
  name='ADD_ENGINE_COMPONENT_LIST',
  full_name='pb.ADD_ENGINE_COMPONENT_LIST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component_list', full_name='pb.ADD_ENGINE_COMPONENT_LIST.component_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=263,
)

_ADD_ENGINE_COMPONENT.fields_by_name['type'].enum_type = _COMPONENT_TYPE
_ADD_ENGINE_COMPONENT_LIST.fields_by_name['component_list'].message_type = _ADD_ENGINE_COMPONENT
DESCRIPTOR.message_types_by_name['ADD_ENGINE_COMPONENT'] = _ADD_ENGINE_COMPONENT
DESCRIPTOR.message_types_by_name['ADD_ENGINE_COMPONENT_ACK'] = _ADD_ENGINE_COMPONENT_ACK
DESCRIPTOR.message_types_by_name['ADD_ENGINE_COMPONENT_LIST'] = _ADD_ENGINE_COMPONENT_LIST
DESCRIPTOR.enum_types_by_name['COMPONENT_TYPE'] = _COMPONENT_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ADD_ENGINE_COMPONENT = _reflection.GeneratedProtocolMessageType('ADD_ENGINE_COMPONENT', (_message.Message,), {
  'DESCRIPTOR' : _ADD_ENGINE_COMPONENT,
  '__module__' : 'Message_pb2'
  # @@protoc_insertion_point(class_scope:pb.ADD_ENGINE_COMPONENT)
  })
_sym_db.RegisterMessage(ADD_ENGINE_COMPONENT)

ADD_ENGINE_COMPONENT_ACK = _reflection.GeneratedProtocolMessageType('ADD_ENGINE_COMPONENT_ACK', (_message.Message,), {
  'DESCRIPTOR' : _ADD_ENGINE_COMPONENT_ACK,
  '__module__' : 'Message_pb2'
  # @@protoc_insertion_point(class_scope:pb.ADD_ENGINE_COMPONENT_ACK)
  })
_sym_db.RegisterMessage(ADD_ENGINE_COMPONENT_ACK)

ADD_ENGINE_COMPONENT_LIST = _reflection.GeneratedProtocolMessageType('ADD_ENGINE_COMPONENT_LIST', (_message.Message,), {
  'DESCRIPTOR' : _ADD_ENGINE_COMPONENT_LIST,
  '__module__' : 'Message_pb2'
  # @@protoc_insertion_point(class_scope:pb.ADD_ENGINE_COMPONENT_LIST)
  })
_sym_db.RegisterMessage(ADD_ENGINE_COMPONENT_LIST)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
