# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WrapMessage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WrapMessage.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  serialized_pb=b'\n\x11WrapMessage.proto\x12\x02pb\"<\n\x0bWrapMessage\x12\x1c\n\x03\x63md\x18\x01 \x01(\x0e\x32\x0f.pb.CommandList\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c*\x87\x01\n\x0b\x43ommandList\x12\x18\n\x14MT_SERVER_TYPE_START\x10\x00\x12\x1b\n\x17MT_ADD_ENGINE_COMPONENT\x10\x01\x12\x1f\n\x1bMT_ADD_ENGINE_COMPONENT_ACK\x10\n\x12 \n\x1cMT_ADD_ENGINE_COMPONENT_LIST\x10\x0b\x42\x06Z\x04.;pbb\x06proto3'
)

_COMMANDLIST = _descriptor.EnumDescriptor(
  name='CommandList',
  full_name='pb.CommandList',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MT_SERVER_TYPE_START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MT_ADD_ENGINE_COMPONENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MT_ADD_ENGINE_COMPONENT_ACK', index=2, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MT_ADD_ENGINE_COMPONENT_LIST', index=3, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=88,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_COMMANDLIST)

CommandList = enum_type_wrapper.EnumTypeWrapper(_COMMANDLIST)
MT_SERVER_TYPE_START = 0
MT_ADD_ENGINE_COMPONENT = 1
MT_ADD_ENGINE_COMPONENT_ACK = 10
MT_ADD_ENGINE_COMPONENT_LIST = 11



_WRAPMESSAGE = _descriptor.Descriptor(
  name='WrapMessage',
  full_name='pb.WrapMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='pb.WrapMessage.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pb.WrapMessage.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=85,
)

_WRAPMESSAGE.fields_by_name['cmd'].enum_type = _COMMANDLIST
DESCRIPTOR.message_types_by_name['WrapMessage'] = _WRAPMESSAGE
DESCRIPTOR.enum_types_by_name['CommandList'] = _COMMANDLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WrapMessage = _reflection.GeneratedProtocolMessageType('WrapMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPMESSAGE,
  '__module__' : 'WrapMessage_pb2'
  # @@protoc_insertion_point(class_scope:pb.WrapMessage)
  })
_sym_db.RegisterMessage(WrapMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
